server:
  port: 8002

spring:
  data:
    mongodb:
      database: dbcatalogo
      port: 27017
    rabbitmq:
      username: guest
      password: guest
      host: localhost
      port: 5672

queue:
  movie:
    name: movieQueue
  serie:
    name: serieQueue

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
message: hello from catalog-service

management:
  endpoints:
    web:
      exposure:
        include: '*'