server:
  port: 8001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_movies?serverTimezone=America/Bogota&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create  
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672

logging:
  level:
    org:
      hibernate:
        SQL: debug

queue:
  movie:
    name: movieQueue
    
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
message: hello from movie-service

management:
  endpoints:
    web:
      exposure:
        include: '*'